[package]
name = "spotify-model"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]

[dependencies]
time = "0.1.37"
reqwest = "0.6.2"
url = "1.5.0"
json = "0.11.6"
log = "0.3"
fern = "0.4"
