[package]
name = "rust-model"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]

[dependencies]
time = "0.1.37"
reqwest = "0.6.2"
url = "1.5.0"
serde = "1.0.8"
serde_derive = "1.0.8"
toml = "0.4.1"
